language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get repository-11
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra
    - addon

before_install:
  - chmod +x gradlew
  # Fix for Constraint Layout
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
   - ./gradlew assembleDebug
