language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools-25.0.4
    - tools
    - tools-26.0.1 # see https://github.com/travis-ci/travis-ci/issues/6040

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra
    - addon

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - chmod +x gradlew
  # Fix for
  # - mkdir "$ANDROID_HOME/licenses" || true
  # - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
